# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: UserInsights
address: >
  Straat<br>
  5100AA Groningen
email: info@userinsights.nl
phone: <a href="tel:+31642131443">+31 (0)6 4213 1443</a>
description: > # this means to ignore newlines until "baseurl:"
  UserInsights biedt inzichten in doelgroepen met behulp
  van verschillende doelgroeponderzoeken en heeft jaren ervaring
  met het neerzetten van kwalitatief onderzoek.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://evaschmitz.github.io" # the base hostname & protocol for your site
brand_name: User<span>Insights</span>

# Build settings
markdown: kramdown
